# Generated by Django 6.1.1 on 2026-09-23 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_number', models.CharField(blank=True, max_length=50)),
                ('initials', models.CharField(blank=True, max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('carrier_name', models.CharField(blank=True, max_length=200)),
                ('main_office_address', models.CharField(blank=True, max_length=300)),
                ('home_terminal_address', models.CharField(blank=True, max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
