# Generated by Django 6.1.1 on 2026-09-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripplanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='commodity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='load_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='shipper',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
